{% set name = "pymbar" %}
{% set version = "3.1.0" %}
{% set sha256 = "7a996e5d3fd8143378f9e18662483446a4a2fe7e57917511e96beb6b07fd6232" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/choderalab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0.0
    - numexpr

test:
  imports:
    - pymbar

about:
  home: http://github.com/choderalab/pymbar
  dev_url: http://github.com/choderalab/pymbar
  doc_url: http://pymbar.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR) method.

extra:
  recipe-maintainers:
    - Lnaden
    - jchodera
    - mrshirts
    - jaimergp
    - mikemhenry
    - ijpulidos
